config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  get 'forecast', to: 'forecast#index'
  post 'forecast', to: 'forecast#index'

  root "forecast#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/climate/daily_weather.rb
# frozen_string_literal: true

#DailyWeather is just a regular ruby class that will eventually make the view cleaner
module Climate
  class DailyWeather
    attr_reader :date, :temp, :min_temp, :max_temp, :extended

    # creating an aray of instances - like a factory
    def self.create_weather_objects(list)
      list.map { |obj| new(obj) }
    end

    def initialize(day)
      @date = day["datetime"]
      @temp = day["temp"]
      @min_temp = day["tempmin"]
      @max_temp = day["tempmax"]
      @extended =  day["description"]

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/forecast_controller.rb
# frozen_string_literal: true

class ForecastController < ApplicationController

  def index
    # Only call service when post message, so the initial get will just display the screen
    if request.post?
      begin
        #create a service instance and execute the call method.
        # The result will be the data and the state of the cache or an error
        result = Climate::ForecastService.new(params[:address]).call

        #in case of an eror from our application we will just have it display in the flash
        if result[:error]
          flash.now[:alert] = result[:error]
        else
          @is_cached = result[:cached] #set is_cached to state of cached for view
          # create an array of DailyWeather objects
          @daily_weather_objects = Climate::DailyWeather.create_weather_objects(result[:data]["days"])
        end
      rescue StandardError=>e #if standarerror thrown from either api we will log it
        logger.error e.message
        flash.now[:alert] = e.message
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forecast/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Weather Forecast</h1>

  <%= form_with url: forecast_path, method: :post, class: "mb-5" do |f| %>
    <div class="input-group">
      <%= f.label :address, "Enter Address:" %>
      <%= f.search_field :address, value: params[:address], class: "form-control" %>
      <div>
        <%= f.submit "Get Weather", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <% if @daily_weather_objects.present? %>
    <div class="card shadow">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Forecast for <%= params[:address] %></h5>
        <% if @is_cached %>
          <span class="badge bg-info text-dark">Result from Cache</span>
        <% else %>
          <span class="badge bg-success">Live Data</span>
        <% end %>
      </div>

      <div class="card-body text-center">
        <h2 class="display-3">Temperature: <%= @daily_weather_objects[0].temp.round %>°F</h2>
        <p class="text-muted">High: <%= @daily_weather_objects[0].max_temp%>° | Low: <%= @daily_weather_objects[0].min_temp%>°</p>
        <p class="text-muted">High: <%= @daily_weather_objects[0].extended %></p>

        <hr>

        <div class="row mt-4">
          <% @daily_weather_objects.each do |day| %> <div class="col">
          <strong><%= day.date %></strong><br>
          <%= day.temp.round %>°
        </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Temperature" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Temperature">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= render "shared/flashes" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <% if type == "notice" %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
      <%= msg %>
     </div>
  <% end %>

  <% if type == "alert" %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <%= msg %>
    </div>
  <% end %>
<% end %>